---
name: Commitlint
on:
  push:
    branches-ignore:
      - 'master'
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: make install
      - name: Commitlint
        run: npx commitlint --color --verbose --from $(git merge-base origin/master HEAD)
