---
name: Continuous Deployment

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: make install
      - run: make compile
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Post-release sync
        run: ./utils/ci/sync.sh
        if: success()
